[project]
name = "chainsmoker"
version = "0.1.0"
description = "A cli interface to find transfer chains for registers"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["rich"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool]
